trigger:
  branches:
    include:
      - main

pool:
  name: alpaca

variables:
  NODE_VERSION: '20.15.0'  

jobs:
- job: Backend
  displayName: 'Build Backend'
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.15.0'  
      displayName: 'Setup Node.js'

    - checkout: self

    - script: |
        cd Backend
        npm ci
      displayName: 'Install Backend dependencies'

    - script: |
        cd Backend
        npm test || echo "No tests defined in Backend"
      displayName: 'Run Backend tests'

    - script: |
        cd Backend
        npm run build || echo "No build script"
      displayName: 'Build Backend'

- job: Frontend
  displayName: 'Build Frontend'
  dependsOn: Backend  
  steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '20.15.0'  # Versión exacta aquí también
      displayName: 'Setup Node.js'

    - checkout: self

    - script: |
        cd frontend
        npm ci
      displayName: 'Install Frontend dependencies'

    - script: |
        cd frontend
        npm test || echo "No tests defined in Frontend"
      displayName: 'Run Frontend tests'

    - script: |
        cd frontend
        npm run build || echo "No build script"
      displayName: 'Build Frontend'