trigger:
  branches:
    include:
      - main

pool:
  name: alpaca

variables:
  NODE_VERSION: '20.x'

jobs:
- job: build_and_test
  displayName: 'Build and Test Job'

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '$(NODE_VERSION)'
    displayName: 'Setup Node.js'

  - checkout: self

  - script: |
      cd Backend
      npm ci
    displayName: 'Install Backend dependencies'

  - script: |
      cd Backend
      npm test || echo "No tests defined in Backend"
    displayName: 'Run Backend tests'

  - script: |
      cd Backend
      if grep -q '"build":' package.json; then npm run build; else echo "No build script"; fi
    displayName: 'Build Backend (if build script exists)'

  - script: |
      cd frontend
      npm ci
    displayName: 'Install Frontend dependencies'

  - script: |
      cd frontend
      npm test || echo "No tests defined in Frontend"
    displayName: 'Run Frontend tests'

  # - script: |
  #     cd frontend
  #     if grep -q '"build":' package.json; then npm run build; else echo "No build script"; fi
  #   displayName: 'Build frontend (if build script exists)'
